version: "3.8"

x-build-ags: &default-build-ags
  DOCKER_BUILD_DEBUG_VERBOSE: ${DOCKER_BUILD_DEBUG_VERBOSE}
  IMAGE_STAGE: ${IMAGE_STAGE}
  IMAGE_VERSION: ${IMAGE_VERSION}
  APP_USER_HOME: ${APP_USER_HOME}
  APP_USER: ${APP_USER}
  APP_USER_ID: ${APP_USER_ID}
  APP_GROUP: ${APP_GROUP}
  APP_GROUP_ID: ${APP_GROUP_ID}

x-ubuntu: &default-ubuntu-image
  build:
    args:
      <<: *default-build-ags
    context: .
    dockerfile: Dockerfile
  working_dir: ${APP_USER_HOME}/${APP_USER}
  tty: true
  stdin_open: true

services:
  ubuntu:
    << : *default-ubuntu-image
    image: "${DOCKER_REGISTRY_WORKSTATION}${IMAGE_NAME}:${IMAGE_VERSION}${VERSION_HASH}"
    container_name: ${IMAGE_NAME}-${IMAGE_VERSION}${VERSION_HASH}
